baseURL = 'http://elisecmorgan.com/'
languageCode = 'en-us'
title = "Elise Morgan's Technical Writing Portfolio"
theme = "Salinger"
copyright = 'Elise Morgan'

[params]
author = "Elise Morgan"
header = "Hi, I'm Elise Morgan. 👋"
description = "I'm a technical writer based in Boulder, CO."
keywords = [ "Portfolio", "technical writer", "documentation", "writer"]
showHeaderOnHomepage = true
twemoji = true

[permalinks]
  '/' = '/:slug/'
  'projects' = '/:slug/'

[Menu]
[[Menu.Main]]
name = "Book 15min Meeting"
url =  "https://calendly.com/elise-morgan-ecm/15-20-minute-screen-chat"
weight = 1

[[Menu.Main]]
name = "Projects"
url = "/projects/"
weight = 2

[taxonomies]
	tag = "tags"
	category = "categories"

[module]
[module.hugoVersion]
extended = false
min = "0.112.0"
[[module.mounts]]
source = "assets"
target = "assets"
[[module.mounts]]
source = "hugo_stats.json"
target = "assets/watching/hugo_stats.json"

[build]
writeStats = true
[[build.cachebusters]]
source = "assets/watching/hugo_stats\\.json"
target = "styles\\.css"
[[build.cachebusters]]
source = "(postcss|tailwind)\\.config\\.js"
target = "css"
[[build.cachebusters]]
source = "assets/.*\\.(js|ts|jsx|tsx)"
target = "js"
[[build.cachebusters]]
source = "assets/.*\\.(.*)$"
target = "$1"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = 'base16-snazzy'
