baseURL = "https://elisecmorgan.com/"
title = "Elise Morgan"
paginate = 5
theme = "PaperMod"
languageCode = 'en-us'
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Elise's Portfolio"
description = "Elise Morgan's Portfolio"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "Elise Morgan"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = true
ShowReadingTime = false
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = false
ShowRssButtonInSectionTermList = false
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = true
showtoc = false
tocopen = false

  [params.assets]
  favicon = "/images/favicon.png"
  favicon16x16 = "/images/favicon.png"
  favicon32x32 = "/images/favicon.png"
  apple_touch_icon = "/images/favicon.png"
  safari_pinned_tab = "/images/favicon.png"

  [params.label]
  text = "Elise Morgan's Portfolio"
  

  [params.profileMode]
  enabled = true
  title = "Hi, I'm Elise Morgan. 👋"
  subtitle = "I am a UX writer, solutions analyst, and documentation specialist based in Boulder, CO. You can reach me at elise.morgan.ecm@gmail.com."
  

    [[params.profileMode.buttons]]
    name = "Projects"
    url = "/projects"

    [[params.profileMode.buttons]]
    name = "Book 15min Meeting"
    url = "https://calendly.com/elise-morgan-ecm/15-20-minute-screen-chat"


  [params.homeInfoParams]
  Title = "Hi, I'm Elise Morgan. 👋"
  Content = "I am a UX writer, solutions analyst, and documentation specialist based in Boulder, CO. You can reach me at elise.morgan.ecm@gmail.com."

  [[params.socialIcons]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/elise-morgan-chica/"

  [[params.socialIcons]]
  name = "GitHub"
  url = "https://github.com/EliseCM"
  


  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]


[markup.highlight]
noClasses = false
